@ECHO OFF

REM Fetching Dust Database
CALL dust.bat

SET LIBRARY_NAME="fftw3"

SET AUTO_LATEST_SRC_URL="TODO"
SET SRC_URL="http://www.fftw.org/fftw-3.3.4.tar.gz"
SET DOWNLOADED_FILE=fftw-3.3.4.tar.gz
SET EXTRACT_COMMAND_UNCOMPRESS=%DUST_7Z% x -aoa fftw-3.3.4.tar.gz
SET EXTRACT_COMMAND_ARCHIVE=%DUST_7Z% x -aoa fftw-3.3.4.tar
SET EXTRACTED_SRC_FOLDER=fftw-3.3.4

SET FFTW3_INSTALL_PREFIX=%DUST_ROOT%/%EXTRACTED_SRC_FOLDER%

CD %DUST_ROOT%

if not exist Compils MKDIR Compils

CD Compils

if exist %DOWNLOADED_FILE% GOTO Label_AlreadyDownloaded

ECHO DOWNLOADING MOFO
wget %SRC_URL%

:Label_AlreadyDownloaded

if exist %EXTRACTED_SRC_FOLDER% GOTO Label_AlreadyExtracted

ECHO EXTRACTING MOFO
%EXTRACT_COMMAND_UNCOMPRESS%
%EXTRACT_COMMAND_ARCHIVE%

:Label_AlreadyExtracted

CD %EXTRACTED_SRC_FOLDER%

REM if not exist build MKDIR build

REM CD build

REM WIP: CODE TO RUN INTO MSYS FOR BUILDING FFTW3 WITH FLOAT (TODO: ADD DOUBLE)
REM WIP: CODE TO RUN INTO MSYS FOR BUILDING FFTW3 WITH FLOAT (TODO: ADD DOUBLE)
REM WIP: CODE TO RUN INTO MSYS FOR BUILDING FFTW3 WITH FLOAT (TODO: ADD DOUBLE)
REM WIP: CODE TO RUN INTO MSYS FOR BUILDING FFTW3 WITH FLOAT (TODO: ADD DOUBLE)

REM IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! IN A SH FILE ! 

%DUST_MSYS_BIN%/sh customFftwConfigureAndBuild.sh

REM WIP: CODE TO RUN INTO MSYS FOR BUILDING FFTW3 WITH FLOAT (TODO: ADD DOUBLE)
REM WIP: CODE TO RUN INTO MSYS FOR BUILDING FFTW3 WITH FLOAT (TODO: ADD DOUBLE)
REM WIP: CODE TO RUN INTO MSYS FOR BUILDING FFTW3 WITH FLOAT (TODO: ADD DOUBLE)
REM WIP: CODE TO RUN INTO MSYS FOR BUILDING FFTW3 WITH FLOAT (TODO: ADD DOUBLE)

:Label_Install

CD %DUST_ROOT%

ECHO You should be right above your newly compiled library (%LIBRARY_NAME%)

:Label_End



