@ECHO OFF

ECHO Setting up Dust distribution

SET DUST_ROOT=C:/Users/Robin/Dust

SET DUST_COMPILER_ROOT=C:/mingw-w64/i686-4.9.2-posix-dwarf-rt_v3-rev0/mingw32
SET DUST_COMPILER_UNIQUE_NAME=i686-4.9.2-posix-dwarf-rt_v3-rev0

REM SET DUST_COMPILER_ROOT=C:/Qt/Tools/mingw482_32
REM SET DUST_COMPILER_UNIQUE_NAME=qt_mingw482_32







REM From this point, DON'T TOUCH ANYTHING !

SET DUST_COMPILER_BINDIR=%DUST_COMPILER_ROOT%/bin

IF "%DUST_MINGW_DISTRIBUTION_SET%"=="TRUE" GOTO Label_DustEnvironment

:Label_MingwEnvironment

SET PATH=%DUST_COMPILER_BINDIR%;%PATH%

set DUST_MINGW_DISTRIBUTION_SET=TRUE



:Label_DustEnvironment

SET DUST_MINGW_ROOT=%DUST_ROOT%/DustMinGW
IF NOT EXIST %DUST_MINGW_ROOT% MKDIR "%DUST_MINGW_ROOT%"

SET DUST_TOOLS_PATH=%DUST_ROOT%/DustTools
IF NOT EXIST %DUST_TOOLS_PATH% (
	ECHO ERROR: Without DustTools subfolder, you won't go nowhere farther.
	GOTO:EOF
)

SET DUST_USR_PATH=%DUST_ROOT%/DustUsr
IF NOT EXIST %DUST_USR_PATH% MKDIR "%DUST_USR_PATH%"

SET DUST_CURRENT_USR=%DUST_USR_PATH%/%DUST_COMPILER_UNIQUE_NAME%
IF NOT EXIST %DUST_CURRENT_USR% MKDIR "%DUST_CURRENT_USR%"

SET DUST_CURRENT_LIBRARY_DEDICATED_USR=%DUST_CURRENT_USR%/PerLibraryUsr
IF NOT EXIST %DUST_CURRENT_LIBRARY_DEDICATED_USR% MKDIR "%DUST_CURRENT_LIBRARY_DEDICATED_USR%"

SET DUST_C_EXE=gcc
SET DUST_CXX_EXE=g++
SET DUST_MAKE_EXE=mingw32-make.exe
SET DUST_AR_EXE=ar.exe

SET DUST_GCC=%DUST_COMPILER_BINDIR%/%DUST_C_EXE%
SET DUST_GXX=%DUST_COMPILER_BINDIR%/%DUST_CXX_EXE%
SET DUST_MAKE=%DUST_COMPILER_BINDIR%/%DUST_MAKE_EXE%
SET DUST_AR=%DUST_COMPILER_BINDIR%/%DUST_AR_EXE%

SET DUST_CMAKE_COMPILER_HINTS=-G"MinGW Makefiles" -DCMAKE_MAKE_PROGRAM="%DUST_MAKE%"

REM Deprecated
SET DUST_CMAKE_MAKE=-DCMAKE_MAKE_PROGRAM=%DUST_MAKE%
SET DUST_CMAKE_GEN=-GMinGW Makefiles




REM External Tools


SET DUST_7Z=%DUST_TOOLS_PATH%/7z

SET DUST_MSYS_ROOT=%DUST_TOOLS_PATH%/msys
SET DUST_MSYS_BIN=%DUST_MSYS_ROOT%/bin


REM TODO

